name: Docker Build and Push
on:
  push:
#      branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name as Docker image tag
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Replace master or main branch with latest tag
        if: env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master'
        shell: bash
        run: echo "BRANCH_NAME=latest" >> $GITHUB_ENV
      
      - name: Store repo name and owner in lower case
        shell: bash
        run: echo "LOWER_CASE_REPO_NAME=$(echo ${GITHUB_REPOSITORY} | tr /A-Z/ /a-z/)" >> $GITHUB_ENV

      ## Configure, build and push docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          # Only push development and main branches
          push: ${{ env.BRANCH_NAME == 'development' || env.BRANCH_NAME == 'latest' }}
          tags: ghcr.io/${{ env.LOWER_CASE_REPO_NAME }}:${{ env.BRANCH_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
